### ISSUE TITLE
Database Exception (#42000) after installing v4.1.0 from source

### ISSUE THREAD

**Issue by moonlies** [CatoTH/antragsgruen#320]
After following the installation instructions for installing antragsgruen v4.1.0 from source and filling in the form of the web installer, Database Exception (#42000) is shown.

OS: Debian 9
Webserver: Nginx

**Comment by CatoTH** [comment]
Could you try if running the following command on the command line in the directory of antragsgruen helps?
```
./yii migrate
```

**Comment by moonlies** [comment]
It shows this error:

`Yii Migration Tool (based on Yii v2.0.15.1)

Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'antragsgruen'@'localhost' for table 'migration'
The SQL being executed was: SHOW FULL COLUMNS FROM `migration`'

in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:664

Error Info:
Array
(
    [0] => 42000
    [1] => 1142
    [2] => SELECT command denied to user 'antragsgruen'@'localhost' for table 'migration'
)`

i have granted all rights to the antragsgruen user on Antragsgrüns database.

**Comment by CatoTH** [comment]
Hm, that's really strange. I'm not really sure, but this kind of looks like a permission problem in the database, as if the user `antragsgruen` didn't have permissions to read tables? Can you check in the `runtime/logs/app.log` if the same messages appear there (i.e. `SELECT command denied`)?

(Anyway, for the problem of the non-applied migrations I'm going to make a bugfix-release today or tomorrow, but I'd rather figure out this issue here first)

**Comment by moonlies** [comment]
Ok, i found the problem and it is a bit embarrassing.
I did
`GRANT ALL ON db TO 'user'@'localhost';`
instead of
`GRANT ALL ON db.* TO 'user'@'localhost';`
now it works. :)
Sorry for the confusion.
