### ISSUE TITLE
Setup DB: Error while install with mariadb

### ISSUE THREAD

**Issue by ManniLoe** [CatoTH/antragsgruen#733]
When installing v4.11.0 the setup throws an error:
`ERROR 1067 (42000) at line 9: Invalid default value for 'dateContentModification'`

The fields dateContentModification are makred as "not null" so we need a "default" value

**Comment by sksksksk** [comment]
the same with mysql  5.7.38
I see that this is fixed in 4.11.1, but I am offered only version 4.11.0 to update, so this hits me.
I tried to modify the migration file m220806_131705_motion_modification_date.php to add the default value, and I see that during the update it is correctly applied, but then again modified. I have the output below. 

So how can I proceed. Is the change in the migration file not enough?

```
*** applied m220730_144556_voting_block_settings_usergroup_order (time: 0.174s)

*** applying m220806_131705_motion_modification_date
    > add column dateContentModification TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER dateResolution to table motion ... done (time: 0.177s)
    > add column dateContentModification TIMESTAMP NOT NULL AFTER dateResolution to table amendment ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dateContentModification'
The SQL being executed was: ALTER TABLE `amendment` ADD `dateContentModification` TIMESTAMP NOT NULL AFTER dateResolution (/home/www/antraege/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /home/www/antraege/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `am...')
#1 /home/www/antraege/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `am...')
#2 /home/www/antraege/vendor/yiisoft/yii2/db/Migration.php(376): yii\db\Command->execute()
```

**Comment by CatoTH** [comment]
@sksksksk did you maybe add the default value only to the first column (for motion), but not for the second (amendment)? Because it looks like the first went through correctly, and it failed on the second. If so, you would need to add it to the second statement, too. (And either undo the change from the first statement, or just uncomment the first line, as it was already executed)

**Comment by sksksksk** [comment]
aaaaa yes! I thought that the 2 statements were identical and it somehow undid the first change. I will try again (I will start from scratch as I restored from a backup). Thank you!
